### ISSUE TITLE
Is there already an existing .java file for using YOLOv7tiny in OpenBot?

### ISSUE THREAD

**Issue by RoBoFAU** [isl-org/OpenBot#334] opened 2023-02-13 11:40 UTC
I want to use my custom trained yolov7 tiny model in Openbot.

Can someone help me with the functions/parameters in the java script required for using that model?

**Comment by thias15** [comment] 2023-02-13 11:54
Are you able to convert into tflite? What does the input and output look like? Are you using the standard Coco labelmap?

**Comment by RoBoFAU** [comment] 2023-02-13 13:00
yes, it is already converted to tflite and I am using the standard coco labelmap.

Which information do you need about input/output?

**Comment by thias15** [comment] 2023-02-14 08:38
Duplicate of #335

**Closed by thias15** 2023-02-14 08:38 UTC
Labels: feature
